<?php

    /**
     * Common strings used as terminology, files, sections and array keys.
     */
    const
        /** @group Routes */
        AUTH            = 'auth',
        AUTHENTICATE    = 'authenticate',
        LOGIN           = 'login',
        LOGOUT          = 'logout',
        REGISTER        = 'register',
        CREATE          = 'create',
        /* @group Configuration Variables */
        PIXII           = 'pixii',
        PIXIIBOMB       = 'PixiiBomb',
        PREFIX          = 'prefix',
        COMPONENT_INSTANCEOF = 'component_instanceof',
        /** @group Database Tables */
        USERS           = 'users',
        /** @group Database Table Columns */
        YOUTUBE         = 'youtube',
        PLAYLISTS       = 'playlists',
        PLAYLIST_ITEMS  = 'playlistItems',
        PLAYLIST        = 'playlist',
        PLAYLIST_ID     = 'playlist_id',
        SERIES_ID       = 'series',
        PID             = 'pid',
        VID             = 'vid',
        PSLUG           = 'playlist_slug',
        PIID            = 'playlist_items_id',
        CID             = 'channel_id',
        CUSTOM_THUMB    = 'use_custom_thumbnail',
        LIKES           = 'likes',
        SERIES          = 'series',
        TAGS            = 'tags',
        VIEWS           = 'views',
        FAVORITES       = 'favorites',
        COMMENTS        = 'comments',
        FREE            = 'free',
        SQUAD           = 'squad',
        APP             = 'app',
        HZD             = 'hzd',
        FFXV            = 'ffxv',
        ROI             = 'roi',
        /** @group Miscellaneous */
        CREATED_AT      = 'created_at',
        UPDATED_AT      = 'updated_at',
        D               = 'default',
        ID              = 'id',
        FIELDS          = 'fields',
        NAME            = 'name',
        META            = 'meta',
        AUTHOR          = 'author',
        KEYWORDS        = 'keywords',
        HEADER          = 'header',
        FOOTER          = 'footer',
        CALLBACK        = 'callback',
        BOOTSTRAP       = 'bootstrap',
        FONT_AWESOME    = 'font-awesome',
        MATERIAL        = 'material',
        TITLE           = 'title',
        SUBTITLE        = 'subtitle',
        DESCRIPTION     = 'description',
        CHAPTERS        = 'chapters',
        DIFFICULTY      = 'difficulty',
        DATE            = 'date',
        UPLOAD          = 'upload',
        PUBLISHED       = 'published',
        THUMBNAIL       = 'thumbnail',
        THUMBNAILS      = 'thumbnails',
        GROUP           = 'group',
        ORDER           = 'order',
        VIDEO_IDS       = 'video_ids',
        CONTENT         = 'content',
        BREADCRUMBS     = 'breadcrumbs',
        PAGE            = 'page',
        NAVBAR          = 'navbar',
        SIDEBAR         = 'sidebar',
        VERTICAL        = 'vertical',
        HORIZONTAL      = 'horizontal',
        BODY            = 'body',
        EXAMPLE         = 'example',
        INDEX           = 'index',
        ERROR           = 'error',
        DATA            = 'data',
        CONTROLLER      = 'controller',
        COMPONENT       = 'component',
        HOME            = 'home',
        DOCS            = 'docs',
        DOCUMENTATION   = 'documentation',
        STYLE           = 'style',
        FILE            = 'file',
        VIEW            = 'view',
        OBJECT          = 'object',
        EMBED           = 'embed',
        SLOT            = 'slot',
        FLUID           = 'fluid',
        NAVIGATION      = 'navigation',
        SUB_NAVIGATION  = 'sub-navigation',
        PRIMARY         = 'primary',
        SECONDARY       = 'secondary',
        ALTERNATE       = 'alternate',
        ACCENT          = 'accent',
        LIGHT           = 'light',
        DARK            = 'dark',
        CUSTOM          = 'custom',
        REQUEST         = 'request',
        DEBUG           = 'debug',
        DETAILS         = 'details',
        BACKTRACE       = 'backtrace',
        TEST            = 'test',
        ITEM            = 'item',
        ITEMS           = 'items',
        CONFIG          = 'config',
        CLASSES         = 'classes',
        ALIAS           = 'alias',
        COLLAPSE        = 'collapse',
        CONTAINER_DATA  = 'container_data',
        INFO            = 'info',
        GUTTERS         = 'gutters',
        WEBP            = 'webp',
        PNG             = 'png',
        GIF             = 'gif',
        JPEG            = 'jpeg',
        JPG             = 'jpg',
        USER            = 'user',
        USERNAME        = 'username',
        PERSONAL        = 'personal',
        EMAIL           = 'email',
        PASSWORD        = 'password',
        DASHBOARD       = 'dashboard',
        CONFIRMATION    = 'confirmation',
        VIDEO           = 'video',
        VIDEOS          = 'videos',
        COUNT           = 'count',
        KBD             = 'kbd',
        ICON            = 'icon',
        BADGE           = 'badge',
        ROUTE           = 'route',
        SLUG            = 'slug',
        SUBMIT          = 'submit',
        POST            = 'post',
        GET             = 'get',
        HASH            = '#',
        FORM            = 'form',
        INPUT           = 'input',
        STORE           = 'store',
        SHOW            = 'show',
        EDIT            = 'edit',
        COMPONENTS      = 'components',
        SITE            = 'site',
        /** @group FOLDERS */
        RESOURCES      = 'resources',
        ERRORS          = 'errors',
        LAYOUT          = 'layout',
        LAYOUTS         = 'layouts',
        /** @group Components */
        ACCORDION       = 'accordion',
        CONTAINER       = 'container',
        CARD            = 'card',
        GRID            = 'grid',
        MISSING         = 'missing',
        /** @group Config */
        FILL            = 'h-100 g-0',
        PY              = 'py-5',
        GUT             = 'g-3',
        PADDING         = 'p-5',
        NOPM            = 'g-0',
        /** @group Errors */
        E400            = 'errors.400',
        E404            = 'errors.404',
        /** @group ENVIRONMENT VARIABLES */
        ENV_DEBUG       = 'APP_DEBUG';

    const
        DEFAULT_APP_SCAFFOLD = 'default-app-scaffold',
        INCLUDE_SITE_NAME_IN_TITLE = 'include-site-name-in-title',
        DEFAULT_NAVBAR_VIEW = 'default-navigation-view',
        INCLUDE_COMPONENT_ALIAS_COMMENT = 'include-component-alias-comment';
